---
title: "Map figures"
author: "Tessa Concepcion"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(tidyverse)
library(ggplot2)
library(sf)
library(ggrepel)

## Set your own WD here ##
setwd("YOUR WD HERE")
knitr::opts_chunk$set(echo = TRUE)

```

```{r Kenya county map}

mapcolors <- c("navy", "coral", "goldenrod")

## Find shapefiles for Kenya and Lake Victoria online and download them.
## Note: I had to keep the files in my download folder because st_read didn't like any "spaces" in the file path
## You only need to perform st_read to the ".shp" file, but the ".shx" and ".dbf" files should also be in the same folder with the same name
## I included Lake Victoria here because the Kenyan county files don't *take out* the space where Lake Victoria is
## Here is where I downloaded my shapefiles from:
## https://open.africa/dataset/kenya-counties-shapefile
## https://www.africageoportal.com/datasets/1c2c6e1107e74e1daef7fb319f1e3553_0/about

kenya <- st_read("C:/Users/tessa/Downloads/kenyan-counties/County.shp")
lake_victoria <- st_read("C:/Users/tessa/Downloads/Lake_Victoria_Shapefile/Lake_Victoria_Shapefile.shp")

## These are the counties I wanted to highlight, change to whichever ones you'd like ##
highlighted_counties <- c("Homa Bay", "Kisumu", "Siaya")
highlighted <- kenya %>% filter(COUNTY %in% highlighted_counties)
centroids <- st_centroid(highlighted) # Picks the center of a county for the label in the map below

## I had to modify the SHP file for Lake Victoria in order to have it match the outline of the Kenya shapefile
## I'm not exactly sure what this is doing, but it worked! If you have any issues with other shapefiles, ask ChatGPT :)
lake_victoria <- st_transform(lake_victoria, st_crs(kenya))
lake_victoria <- st_make_valid(lake_victoria)

## This "cuts out" the shape of Lake Victoria to the match the shape of Kenya
lake_victoria_kenya <- st_intersection(lake_victoria, kenya)


## Plot map
ggplot(data = kenya) +
  geom_sf(fill = "gray95", color = "black") +  # Base map
  geom_sf(data = highlighted, fill = mapcolors, color = "black") +  # Highlighted counties
  geom_sf(data = lake_victoria_kenya, fill = "turquoise4", color = "black") +  # Lake Victoria overlay
  geom_label_repel(data = centroids, 
                   aes(x = st_coordinates(geometry)[,1], 
                       y = st_coordinates(geometry)[,2], 
                       label = COUNTY ), 
                   color = "black", 
                   fill = "white",
                   size = 4, 
                   fontface = "bold", 
                   box.padding = 1, # Amount to "repel" the label
                   min.segment.length = 1, # Should match the padding above, if you want the line to connect
                   segment.size = 1.5, # Makes the line to the label thicker
                   label.r = 0) + # Makes the edges of the label square
  theme_minimal()+
  labs(x="", y="")

ggsave("Location to save your file", width=6, height=6)

```
